### ISSUE TITLE
Не присылает готовое предложение обмена в лс/группу.

### ISSUE THREAD

**Issue by Wifelly** [Iriskin0/Chat-Wars-Bot#100]
Не присылает готовое предложение обмена в лс/группу.
Выдает ошибку:
> coroutine: 'NoneType' object has no attribute 'id'

**Comment by mnb3000** [comment]
О баге знаю, скоро пофикшу

**Comment by iglotov** [comment]
Возможно, что отсюда же: при запуске с указанием группы ругается "Cannot find dialog with props: {'id': blablabla}. Trying InputPeerChat". Ну и на приказы в группе, соответственно, не реагирует.

**Comment by Loskir** [comment]
Не, это не оттуда

**Comment by Loskir** [comment]
Это вполне нормально

**Comment by Loskir** [comment]
Он может не найти диалога с ойстером/красным ботом, все равно он ему не нужен

**Comment by Loskir** [comment]
уже пофикшено, думаю можно закрыть
