### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by 3mph4515** [Iriskin0/Chat-Wars-Bot#102]
Обновите ридми. Слишком много каких-то странных вещей происходит.
Например, бот теперь пытается реквестнуть авторизацию и запрашивает код у телеграмма для логина. (Кстати, не работает из-за двухфакторной авторизации) 

> Ошибка coroutine: (SessionPasswordNeededError(...), 'Two-steps verification is enabled and a password is required.')

**Comment by mnb3000** [comment]
Сейчас эта версия в разработке и перенесена в новую ветку, сделайте `git pull` чтобы откатиться на рабочую версию

**Comment by mnb3000** [comment]
Предлагаю реопен для обновления ридми в телетон версии

**Comment by mnb3000** [comment]
Двухфакторная уже пофикшена в телетон ветке если что

**Comment by 3mph4515** [comment]
Круто, потещу тогда. Я вообще долго думал, что меня хакают какие-то плохие ребята (приходили коды телеграмма). Пока логи бота не почитал :)

**Comment by mnb3000** [comment]
Она пока очень сырая и новые функции через раз работают, так что гуд лак

**Comment by Loskir** [comment]
вроде теперь должно норм работать, можно тестить

**Comment by Loskir** [comment]
Done
