### ISSUE TITLE
Команды боту

### ISSUE THREAD

**Issue by c01d-SINtez** [Iriskin0/Chat-Wars-Bot#103]
Доброго времени суток. Не могу разобраться как и куда вводить команды боту, те что вида #ping. Пробовал в чат сам с собой, не работает.

**Comment by Loskir** [comment]
Нужно, чтобы команды были от того, кто прописан в --admin

**Comment by c01d-SINtez** [comment]
прописывать юзернейм телеграма или ник в ЧВ?

**Comment by Loskir** [comment]
Юзернейм без @

**Comment by c01d-SINtez** [comment]
пробовал через --, прописывал в самом скрипте. Пишу #ping в чат самого себя, ничего

**Comment by N1k0lay** [comment]
Ошибок при запуске есть какая нибудь? Была такая проблема, -- сливались в длинный тире. Бота запускаешь для себя?

**Comment by Loskir** [comment]
+ регистр важен

**Comment by c01d-SINtez** [comment]
нет, ошибок ноль, всё прекрасно работает. Бота запускаю от себя. Сейчас админ и прочие настройки прописаны в самом скрипте, запускаю без аргументов.

**Comment by Loskir** [comment]
Груп нейм указан?

**Comment by c01d-SINtez** [comment]
да. И туда приходят форварды от боссов в лесу

**Comment by c01d-SINtez** [comment]
Уточню на всякий случай. Команды боту нужно писать самому себе, так?

**Comment by Loskir** [comment]
Неважно куда, главное от себя

**Comment by c01d-SINtez** [comment]
если я @vasya, то прописал vasya в скрипте и от него же и даю команду

**Comment by Iriskin0** [comment]
Регистр при написании ника соблюдаешь?
Vasya не то же самое, что vasyA

**Comment by c01d-SINtez** [comment]
само собой, ник прописан корректно. Сейчас закинул бота для проверки на основной акк - всё работает. Видимо я где-то ошибся вначале. Спасибо за помощь.
