### ISSUE TITLE
Ошибка coroutine: name 'endurancetop' is not defined

### ISSUE THREAD

**Issue by appossumm** [Iriskin0/Chat-Wars-Bot#107]
Подскажите пожалуйста, что за ошибка возникает? Бот работает на #ping отзывается.
По команде #stock выдает "Я еще не дорос, у меня только 0 уровень"

**Comment by Loskir** [comment]
Telethon или cli?

**Comment by Loskir** [comment]
Переходи на Telethon, у cli хотфикс кривой

**Comment by appossumm** [comment]
Спасибо....
