### ISSUE TITLE
Ввод телефона в параметры запуска

### ISSUE THREAD

**Issue by Wifelly** [Iriskin0/Chat-Wars-Bot#109]
Не особо удобно при первичном логине на новой версии вводить номер. Да и прописывать код от телеги тоже тот ещё ад. Предлагаю, офк, если это возможно, вернуть старый способ, когда бот сам определял номер и получал код за тебя.

**Comment by Loskir** [comment]
Ээээ, тогда нужно сначала логинить cli, а это тот ещё адище

**Comment by Wifelly** [comment]
А, тоесть теперь в cli можно не логиниться? Онли в боте? Он автоматом войдет под указанным телефоном?

**Comment by Loskir** [comment]
ну не автоматом, если до этого не логинился, то нужно код таки ввести, но да, кли больше не нужен

**Comment by Wifelly** [comment]
Ну, без кода то никуда.
Окей. Спасибо за ответ. Закрываю
