### ISSUE TITLE
Новые кнопки Атаки и Защиты

### ISSUE THREAD

**Issue by ViktorRel13** [Iriskin0/Chat-Wars-Bot#120]
Новый кнопки Атаки и Защиты:
"🛡Встретить гостей" работает простой заменой в начале бота, "⚔️Пойти в гости" так не работает

**Comment by Iriskin0** [comment]
Это эвент

**Comment by ViktorRel13** [comment]
@Iriskin0 да, но по факту получается, что атаки не срабатывают - просто флаг игра игнорирует чаще всего, ей надо перед этим атаку прожать. Остаётся только деф.
Похоже аналог "⚖️" и "📊" для биржи

**Comment by Fenicu** [comment]
во orders можешь вручную прописать.
что бы не парится сильно, подключись к серверу с телефона и с помощью nano например перекопируй всё в скрипт. Там есть символ который копируется только с телефона (проверял на андройде, работает).
