### ISSUE TITLE
0 лвл

### ISSUE THREAD

**Issue by Fenicu** [Iriskin0/Chat-Wars-Bot#125]
в общем замечено на многих фермах, что иногда твины не адекватно лвл определяют, когда запрашиваешь обновить сток, пишут 0 лвл. Лечиться многочисленными ребутами и постоянно разные падают с этой проблемой. Так же телеграм-кли иногда любит пожрать 10-20-30% оперативки от сервера в 1-3 клиента и сервера падает ... Какие есть решения этих проблем?

**Comment by Loskir** [comment]
ливать из чв 💯

**Comment by Iriskin0** [comment]
телеграм кли вообще страшная штука. Лучше всего, конечно, переехать на телетоновский клиент, если он есть

**Comment by Fenicu** [comment]
телетон клиент ещё более нестабилен, он падает каждые 3-4 часа, стабильно

**Comment by Loskir** [comment]
зато не жрет

**Comment by Fenicu** [comment]
всё таки большой резон на телетон переезжать?.. ща буду тестить, а вы пользуетесь им то или на кли всё хорошо?

**Comment by Loskir** [comment]
Лично у меня все ооочень давно нафиг стоит

**Comment by Iriskin0** [comment]
У телетона больше функций, больше потенциал. А насчет вылетов смотреть нужно
Сам не пользуюсь ни тем, ни другим - забросил чв
