### ISSUE TITLE
Отправка команд

### ISSUE THREAD

**Issue by flomazter** [Iriskin0/Chat-Wars-Bot#18]
Добавьте пожалуйста возможность отправки команд. 
Допустим
 #send_order Команда(той что нет в списке возможных команд) 
например для покупки чего-либо или одевания или внимания шмота, в общем было бы удобно иметь возможность сразу отправить команду.

**Comment by Iriskin0** [comment]
Попробую костыль накидать, но работать наверн не очень будет

**Comment by flomazter** [comment]
Предполагаю можно сделать на основе #push_order только не совсем разобрался с функцией update_order
Я так предполагаю что есть некоторая очередь команд, но как она реализована ни как не могу разобраться

**Comment by Storhayer** [comment]
можно дописать своих команд. мне, например ордер не удобен на телефоне + немного человечности. таким макаром и добавляешь своих команд
            elif text == 'Форвард':
                send_msg(bot_username, '🏅Герой')
                sleep(2)
                send_msg(bot_username, '/hero')
                sleep(3)
                fwd(order_usernames, hero_message_id)
            elif text == 'Пещера':
                send_msg(bot_username, '🗺 Квесты')
                sleep(10)
                send_msg(bot_username, '🕸Пещера')
            elif text == 'Лес':
                send_msg(bot_username, '🗺 Квесты')
                sleep(10)
                send_msg(bot_username, '🌲Лес')

**Comment by forentfraps** [comment]
Дравствуйте, не очень понял как отправлять команды боты

**Comment by forentfraps** [comment]
в саму консоль пишу, бот не реагирует
из самого телеграмма тоже

**Comment by mnb3000** [comment]
Вроде как закрыто командой #eval
