### ISSUE TITLE
Парсинг команд боту об атаке\защите из супергрупп

### ISSUE THREAD

**Issue by sorupopic** [Iriskin0/Chat-Wars-Bot#21]
Если в order_usrnames прописан юзер и он соcтоит в одной группе с игроком, то команды работают.
В супергруппе не работают.

**Comment by Storhayer** [comment]
да, проблема очень актуальна

**Comment by 220242** [comment]
попробуйте использовать этот тг https://github.com/SEEDTEAM/tg/

**Comment by Iriskin0** [comment]
@220242 не похоже, чтоб туда добавляли супергруппы

**Comment by 220242** [comment]
Это из воспоминаний овер год назад) Что то нужно было и вроде бы seedteam работал в супергруппах.

**Comment by Storhayer** [comment]
на самом деле все работает, не работают кнопки для пересыла инлайнов. а так, если командир присылает флаг, то все работает
