### ISSUE TITLE
Помогите с командами!

### ISSUE THREAD

**Issue by DarkSunny** [Iriskin0/Chat-Wars-Bot#23]
Ребята, помогите новичку в Ибунту :)  Всё настроил, телега работает, бота запустил, тоже работает, но ни как не могу понять как послать команду к примеру отключения пещеры, что бы ходил только в лес, не могу понять куда именно отправлять эту команду и в каком виде, буду очень признателен вам за помощь!

**Comment by iOzerman** [comment]
Команды отправляются пользователем, указанным в --admin
То есть можешь сам себе в личку писать.
Я добавил несколько изменений в код бота, если автор их примет - будут походы в пещеры и в лес. Сейчас ходит только в пещеры.
