### ISSUE TITLE
Не могу запустить из-за кодировки

### ISSUE THREAD

**Issue by karopka** [Iriskin0/Chat-Wars-Bot#26]
При попытке стартануть бота ругается:
{'id': 265204902, 'flags': 4352, 'last_name': '', 'print_name': 'Chat_Wars', 'username': 'ChatWarsBot', 'first_name': 'Chat Wars', 'type': 'user'}
Unhandled exception in thread started by <function queue_worker at 0x7f1698187d90>
Traceback (most recent call last):
  File "./main.py", line 140, in queue_worker
    print(sender.contacts_search(captcha_bot))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 65-74: ordinal not in range(128)

Стартую так python3 ./main.py --admin somebot1 --order MasterZZ --castle blue --gold 0

**Comment by Iriskin0** [comment]
Скорее всего проблемы с кодировкой на сервере. Кодировка системы должна быть UTF-8

**Comment by karopka** [comment]
#locale -a
C
C.UTF-8
POSIX

**Comment by Iriskin0** [comment]
Это весь вывод? ru-RU.utf8 поддержку наверно надо добавить

**Comment by 3mph4515** [comment]
Было такое на сервере, проблему решил установкой языковых пакетов каких-то русских. 
Вообще было бы неплохо убрать все русские символы. Могу заняться этим

**Comment by adascal** [comment]
Эммм...)) И как потом тексты читать?)

**Comment by 3mph4515** [comment]
@adascal Да, что-то забыл, что бот на русском, отмена 👎

**Comment by karopka** [comment]
отпишусь как попробую кодировки) спасибо!

**Comment by karopka** [comment]
команда ./main.py --admin somebot1 --order MasterZZ --castle blue --gold 0

теперь вот такой вывод:
./main.py: line 2: from: command not found
./main.py: line 3: from: command not found
./main.py: line 4: from: command not found
./main.py: line 5: from: command not found
./main.py: line 6: from: command not found
./main.py: line 7: from: command not found
./main.py: line 8: from: command not found
./main.py: line 9: import: command not found
./main.py: line 10: import: command not found
./main.py: line 11: import: command not found
./main.py: line 12: import: command not found
./main.py: line 13: import: command not found
./main.py: line 16: bot_username: command not found
./main.py: line 19: admin_username: command not found
./main.py: line 22: order_usernames: command not found
./main.py: line 25: castle_name: command not found
./main.py: line 27: captcha_bot: command not found
./main.py: line 30: socket_path: command not found
./main.py: line 33: host: command not found
./main.py: line 36: port: command not found
./main.py: line 38: syntax error near unexpected token `('
./main.py: line 38: `opts, args = getopt(sys.argv[1:], 'a:o:c:s:h:p:g', ['admin=', 'order=', 'castle=', 'socket=', 'host=', 'port=', 'gold='])'

**Comment by Iriskin0** [comment]
./main.py --admin "somebot1" --order "MasterZZ" --castle "blue" --gold 0

**Comment by karopka** [comment]
тоже самое... :(

**Comment by Iriskin0** [comment]
то же самое, что и в первом сообщении или где command not found?

**Comment by karopka** [comment]
command not found

**Comment by Iriskin0** [comment]
попробуй просто запустить ./main.py

**Comment by karopka** [comment]
![image](https://cloud.githubusercontent.com/assets/18676256/25119112/fcfd00ba-2429-11e7-9313-600778927285.png)
команда не найдена. 

Шаги: 
Устанавливаем pip3: sudo apt-get install python3-pip
Устанавливаем pytg для 3 питона: pip3 install pytg pytz

Выполнены.

**Comment by Iriskin0** [comment]
а, блин. python3 ./main.py --admin "somebot1" --order "MasterZZ" --castle "blue" --gold 0
:D

**Comment by karopka** [comment]
Получил теперь такое:
 Ошибка очереди: Error 71: 'RPC_CALL_FAIL 400: YOU_BLOCKED_USER' (command "[disable_preview] msg @ChatWarsBot '\U0001f3c5Герой'\n")

:).. Разблокировать уже никак?

**Comment by Iriskin0** [comment]
Бота разблокируй

**Comment by karopka** [comment]
Спасибо всем. Был заблокирован не бот, а мой акк. А я и не заметил.
