### ISSUE TITLE
сломались сокеты

### ISSUE THREAD

**Issue by iglotov** [Iriskin0/Chat-Wars-Bot#37]
Отвалился функционал соединения с tg-cli через сокет.
```
Traceback (most recent call last):
  File "./main.py", line 132, in <module>
    sender = Sender(sock=socket_path) if socket_path else Sender(host=host,port=port)
TypeError: __init__() got an unexpected keyword argument 'sock'
```
В чём может быть дело?

**Comment by Iriskin0** [comment]
у меня не работал %)
попробуй через порты

**Comment by its-me** [comment]
Нужно смежить это и тогда работает: https://github.com/luckydonald/pytg/pull/107

**Comment by adascal** [comment]
На сколько я помню, у меня тоже этот ПР подтянут, так что должно помочь

**Comment by iglotov** [comment]
Дык в том и дело, что оно работало, ребят. Но когда я подтянул актуальную версию — перестало. :(  Уточню, pytg и telegram-cli остались прежними, обновился только бот.

**Comment by its-me** [comment]
Дык, в том и дело, что именно твоя ошибка возникает если этот ПР не смержен.

**Comment by iglotov** [comment]
Спасибо, вопрос закрыт. Не очень понятно, что произошло, но факт — ваше решение рабочее.
