### ISSUE TITLE
Поимка лесного зверя в соло/группой

### ISSUE THREAD

**Issue by Isidroalex** [Iriskin0/Chat-Wars-Bot#43]
Введен доп контент, когда после похода в лес выдается ссылка на драку с монстром.
Предлагаю реализовать для соло боя (поиск в сообщении "/fight...." и отправка боту

По возможности, мб пересылка кому-то в группу или личку.

**Comment by VerTox** [comment]
Так введено уже, и даже работает, бот сразу тыкает на ссылку и форвардит админу/в группу

**Comment by Nikolaz81** [comment]
А если задать группу для ботов, и ботов перечислить в ключе order, то они
ещё и помогать будут друг другу. Правда тут возникает проблема: при запросе
статуса в  ответ приходит сообщение с пиктограммами, и боты их принимают за
команды. В планах сделать отдельный ключ для перечисления только помощников
для исправления этого бага.

**Comment by VerTox** [comment]
А не проще чекать сообщения из управляющей группы и если там есть "/fight" то ломиться на помощь?

**Comment by Nikolaz81** [comment]
Думал об этом, но надо логику приёма сообщений переделывать, т.к.
отправитель может быть любой, важна только группа получатель.

**Comment by VerTox** [comment]
Так он в любом случае все сообщения дергает, просто проверять сообщения и от бота и от группы

**Comment by VerTox** [comment]
Но это не так актуально как убрать задрачивание команды "Герой", как собственно Ко и палит ботов

**Comment by Isidroalex** [comment]
Действительно реализовано, просто отсутствовало в описании
