### ISSUE TITLE
Борьба с монстрами

### ISSUE THREAD

**Issue by KoltsovV** [Iriskin0/Chat-Wars-Bot#44]
Сделать отправку и прием команд если в лесу встречен монстр

**Comment by iglotov** [comment]
1. уже сделано
2. видимо, пора в приватный репо переезжать

**Comment by Iriskin0** [comment]
@iglotov приватка есть для новой версии, но штота она не пишется :(

**Comment by adascal** [comment]
Моя еще как пишется 😂
