### ISSUE TITLE
Форвард приказа

### ISSUE THREAD

**Issue by Storhayer** [Iriskin0/Chat-Wars-Bot#46]
Приказ приходит инлайном, а телега эту фишку не поддерживает и хз что делать. Форвард по ИД сообщения не работает, т.к. не понимает как форвардить непонятное. Есть ли может патчи какие для телеги с поддержкой новых фишек?

**Comment by VerTox** [comment]
Вроде был форк telegram-cli с поддержкой инлайна, но это не точно

**Comment by adascal** [comment]
Вот тоже пришлось делать костыли, просто уповать, что это нужная инфа и пернсылать на прямую

**Comment by Storhayer** [comment]
как? не могу ни инлайн, ни пин форварднуть никак...

**Comment by adascal** [comment]
Я просто доверяю боту, что шлет этот приказ. Все, что бы он не слал и если это сообщение не имеет текста, я просто форвард делаю. С каким ботом проблема?

**Comment by Storhayer** [comment]
так в этом и проблема, что отдельно никакой бот не шлет ничего. в чат отряда приходит инлайн, потом бот делает пин, но т.к. телега-цли старая, то она не понимает инлайнов((
.jn который присылал раньше сейчас не всегда шлет, а в чатике приказы всегда... мне по сути только для этого бот и нужен, ну, +арена

**Comment by adascal** [comment]
Если я правильно понял с каким ботом проблема, то можно просто форвардить то, что шлет этот бот в чате боту игры и он поймет, именно так работает у меня

**Comment by Storhayer** [comment]
Можешь кусок кода скинуть? Телеграм тот, что тут или форк?
