### ISSUE TITLE
автопрокачка

### ISSUE THREAD

**Issue by iglotov** [Iriskin0/Chat-Wars-Bot#47]
несколько раз уже наткнулся. автокач дефа работает, а вот с атакой не получается. грешил на несовпадение символа — не смог обнаружить разницы между отправляемой ботом командой, и командой с кнопки. соответственно, пока не получится прокачать атаку, бот пытается это сделать и не расходует стамину.
скрин ниже. первая команда от бота, вторая мышкой. 
<img width="531" alt="2017-05-13 21 12 21" src="https://cloud.githubusercontent.com/assets/5945071/26026227/c254c496-3821-11e7-855e-c325553b2823.png">

/level_up
+1 ⚔️Атака

/level_up
+1 ⚔️Атака

**Comment by chrme** [comment]
там просто в коде ошибка, между значком и словом атака лишний символ

**Comment by adascal** [comment]
Не известно, у меня такая же проблема наблюдается на моей версии. Копировал оригинальное значение из бота, сравнивал их, все еднтично, лишних символов нет, но с атакой и правда проблема

**Comment by adascal** [comment]
Короче, удаление лишнего символа помогло, странно, ведь только так эмоджи корректно формируется, но видать там свои мысли у Кольцова :)

**Comment by Bober88** [comment]
какой конкретно символ удалил?

**Comment by Iriskin0** [comment]
сделайте пулл реквест пож

**Comment by chrme** [comment]
сделал
