### ISSUE TITLE
TelegramAPI

### ISSUE THREAD

**Issue by Storhayer** [Iriskin0/Chat-Wars-Bot#48]
Кстати, а есть возможность запуска бота на АПИ под простым юзером? Это могло бы облегчить вообще всё, да и запуск под Вин был бы осуществим...

**Comment by WinnerOK** [comment]
На Windows 10 можно запустить бота. Просто нужно [активировать подсистему linux](https://habrahabr.ru/company/eset/blog/281418/)

**Comment by adascal** [comment]
Согласен, на Вин 10 не пробовал, но должно работать хорошо.

**Comment by Storhayer** [comment]
да, на 10 вроде как должно все пахать, но старый цли не понимает новые фичи телеграма, а это печально

**Comment by WinnerOK** [comment]
Пока tdlib не будет выпущена, обновление к cli не будет. 

[источник](https://github.com/vysheng/tg/issues/1189#issuecomment-260792808)

**Comment by VerTox** [comment]
натыкался тут на одну упоротую версию бота, как раз на апи работающую и вполне под виндой, https://github.com/japonskygorodovoy/autoclient но её пилить и пилить еще, к слову она умеет(теоретически) инлайн сообщения

**Comment by fangelion** [comment]
autoclient сложно запускать. Там на каждый логин надо вручную добывать api_id

**Comment by Iriskin0** [comment]
@fangelion одного достаточно на все логины
