### ISSUE TITLE
Ошибка coroutine. Не создает файл конфига

### ISSUE THREAD

**Issue by Gr33ner** [Iriskin0/Chat-Wars-Bot#49]
Добрый день! Как исправить ошибку?
Ошибка coroutine: [Errno 2] No such file or directory: './bot_cfg/95351827.cfg'

**Comment by Iriskin0** [comment]
Папки bot_cfg нет?

**Comment by Gr33ner** [comment]
разобрался, скрипт не мог найти путь до папки. указал ручками :)
