### ISSUE TITLE
несколько копий telegram-cli

### ISSUE THREAD

**Issue by Bober88** [Iriskin0/Chat-Wars-Bot#50]
Поделитесь подробной инфой, как запустить больше одного telegram-cli на одной машине (ubuntu server 16.04.02). Спасибо!

**Comment by VerTox** [comment]
Все до безобразия просто.
Открываешь  ~/.telegram-cli/config
пишешь туда:
```
profile_1 = {
config_directory = ".telegram-cli/profile_1";
msg_num = true;
};
```
столько раз, сколько нужно инстансов телеграма, естественно меняя название профиля и путь.
после этого запускаешь телеграм:
`./bin/telegram-cli -W -p profile_1 -P 1390 --json`
естественно для каждого профиля свой порт.

**Comment by Bober88** [comment]
Спасибо! всё отлично работает!
