### ISSUE TITLE
указание группы для отправления батлов

### ISSUE THREAD

**Issue by Loskir** [Iriskin0/Chat-Wars-Bot#51]
возможность добавить группу, в которую боты будут кидать своих монстров и читать оттуда же для помощи

**Comment by VerTox** [comment]
Они и так кидают в группу, а вот читать, там ад и Израиль начнётся, игровой бот иногда ласты заворачивает и не выдаёт итоги битвы если несколько игроков одновременно пришли на помощь

**Comment by N1k0lay** [comment]
Как они кидают и как читают? Что для этого нужно настроить?
