### ISSUE TITLE
Общий сток твинков

### ISSUE THREAD

**Issue by Storhayer** [Iriskin0/Chat-Wars-Bot#54]
Добавил twinkstock_enabled = False (по умолчанию всегда выключен, чтоб не слал сток каждый раз когда торговля нужна) и global twinkstock_enabled в нужном месте (хз как объяснить куда, т.к. все перелопачено в своем боте)
            elif text == '#stock':
                twinkstock_enabled = True
                send_msg('@' , 'ChatWarsTradeBot', '/start')  

И потом еще этот блок:
    elif username == 'ChatWarsTradeBot' and twinkstock_enabled:
        if text.find('Твой склад с материалами') != -1:
            stock_id = message_id
            fwd('@' , 'PenguindrumStockBot', stock_id)
            twinkstock_enabled = False
            send_msg('' , group_name, 'Сток обновлён!')

чтоб нормально работало надо зарегить всех твинков в PenguindrumStockBot, ну и соответственно смотреть сумму стоков потом уже в нем

**Comment by allion** [comment]
Сделано, можно закрывать
