### ISSUE TITLE
Проверка наличия отправляемой кнопки

### ISSUE THREAD

**Issue by andmarkelov** [Iriskin0/Chat-Wars-Bot#58]
Крайне необходимо это сделать, поскольку я помню, как в один прекрасный день Кольцов начал экспериментировать и добавлял в кнопки латинские символы. Но в скрипте я такой проверки не нашёл. И вообще, похоже, в Telegram-CLI нельзя их получить вместе с сообщением. Или возможно?

**Comment by Iriskin0** [comment]
В текущем кли нельзя получить кнопки

**Comment by andmarkelov** [comment]
Жаль (
