### ISSUE TITLE
модификация

### ISSUE THREAD

**Issue by Loskir** [Iriskin0/Chat-Wars-Bot#63]
### модифицировал бота:

1. Он стал проверять профиль чаще (5-10 мин), а то не дело 4 раза в час на стройку ходить

2. #61 Если не хватает денег на стройку, пытается задонатить 10 монет и сходить еще раз, правда не смог научить его чекать, что именно закончилось, поэтому если закончится лес или горы то он просто задонатит все в казну

3. #62 Научил его не ходить в лес за несколько секунд до битвы и улучшил regex (заменил `{0,1}` на `?`)

4. Теперь он ходит по стройкам-лесам вплоть до 15 минут до битвы

5. Убрал поход на стройку через меню замка, ведь все ходят по командам (мб нет)

![image](https://cloud.githubusercontent.com/assets/21295738/26820866/161069c6-4aad-11e7-9216-45f25aa56752.png)

**Comment by Loskir** [comment]
упс, не донатит в казну

**Comment by VerTox** [comment]
1. зачем вообще? чтобы бот был еще более палевным?

**Comment by Loskir** [comment]
Ну я не знаю, я и руками так делаю

**Comment by N1k0lay** [comment]
Всё окей. Все командами пишут. Как часто он ходит строиться? Постройка включена, но вот строительство не идет.
