### ISSUE TITLE
Репорты

### ISSUE THREAD

**Issue by N1k0lay** [Iriskin0/Chat-Wars-Bot#69]
Есть возможность реализовать репорты о строительстве, битве, дуэле в бот отряда?

**Comment by allion** [comment]
Для красного репорты стройки и боя есть, для остальных замков нужны боты. Ну или переделать по аналогии.
Репорты арен нафиг, шуметь будут. Есть команда #info

**Comment by N1k0lay** [comment]
Удобно было бы просто вписывать бота своего отряда и чтобы туда отправлялись данные.

**Comment by iglotov** [comment]
Можно логику работы с красным ботом немного перекроить? Вместо Легата, как я понимаю, для стока и репортов будет использоваться Red Castle Bot, который (beta), но ему нужно еще и результат /hero отправлять. @allion же Легата добавлял в код?

**Comment by mnb3000** [comment]
Закрыто легату и ойстеру
