### ISSUE TITLE
Парс сообщения с inline кнопкой

### ISSUE THREAD

**Issue by 3mph4515** [Iriskin0/Chat-Wars-Bot#71]
Тот же легат сейчас присылает приказ на атаку с инлайн-кнопкой. Telegram-cli вообще не видит такого сообщения. Есть варианты как распарсить такое сообещение?

**Comment by kriklivsky** [comment]
tg-cli не видит этих сообщений. поэтому нет вариантов.

**Comment by VerTox** [comment]
варианты есть всегда. можно сделать/найти телеграм бота, который просто пересылает то-же что ему отправили, и все сообщения у которые не распознаются, слать ему, и оттуда уже дергать содержание сообщения.

**Comment by 3mph4515** [comment]
@VerTox Не совсем понял. Из легата отправить в какого-то бота и там преобразовать в сообщение, которое бот понимает? А как отправить-то из легата в другого бота

**Comment by VerTox** [comment]
if msg['event'] == 'message' and 'text' in msg and msg['peer'] is not None:
 {.....}
elif msg['event'] == 'message' and msg['sender']['username'] == ЛЕГАТ_БОТ:
   {форвардим сообщение нужному боту}

**Comment by 3mph4515** [comment]
Сообщения с инлайн-кнопками вообще до cli не доходят :(

**Comment by VerTox** [comment]
А у меня доходят

**Comment by mnb3000** [comment]
Будет сделано в ближайших патчах телетон версии

**Comment by AHAXPOHOC** [comment]
и вопрос в догонку..
что за "телетон версия" и где её взять?)
я наивно полагал, что можно поискать у mnb3000 на странице... но ошибся))
покопался в самом коде - тоже, казалось бы, пусто..
я просто слепой?

**Comment by eko24ive** [comment]
шо там ребзя, есть инфа по инлайн хендлингу ?

**Comment by Iriskin0** [comment]
@eko24ive в телетон приватке все ок

**Comment by eko24ive** [comment]
что ты имеешь в ввиду по "приваткой" ?

**Comment by AHAXPOHOC** [comment]
Eko,
стягиваешь себе, откатываешься на пару коммитов назад, ищешь подключение telethon, правишь, запускаешь.
и тогда работает, да...

**Comment by eko24ive** [comment]
меня интересует конкретно работа с инлайн кнопками

**Comment by AHAXPOHOC** [comment]
telegram-cli не поддерживает работу с кнопками в сообщениях, для этого нужен teleton
в руки гугл. мне помогло,...

**Comment by eko24ive** [comment]
единственное что нашёл это - https://github.com/LonamiWebs/Telethon/issues/98

**Comment by Iriskin0** [comment]
@eko24ive https://lonamiwebs.github.io/Telethon/methods/messages/send_inline_bot_result.html
Чет типа того.
Под "приваткой" имею в виду закрытую разработку, уехавшую в другие репозитории, без меня

**Comment by Iriskin0** [comment]
@eko24ive а, я там в комментах отписался оказца :))
https://lonamiwebs.github.io/Telethon/methods/messages/get_bot_callback_answer.html

**Comment by eko24ive** [comment]
понял, и на этом спасибо. хотелось бы конечно получить код, который можно было бы закопипастить

**Comment by AHAXPOHOC** [comment]
ничто в этом мире не даётся просто так....
вообще, в комментах тут поищи. кидали ник чувака с приватками.. может и договоришься)

**Comment by eko24ive** [comment]
маякнул чуваку - буду ждать ответа )

**Comment by 3mph4515** [comment]
CLI никогда уже не будет парсить инлайны.
